# Generated by Django 4.2.3 on 2023-07-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='media/pdf')),
                ('fb_URL', models.URLField(blank=True, null=True, verbose_name='FACEBOOK URL')),
                ('tw_URL', models.URLField(blank=True, null=True, verbose_name='TWITTER URL')),
                ('lk_URL', models.URLField(blank=True, null=True, verbose_name='LINKEDIN URL')),
                ('insta_URL', models.URLField(blank=True, null=True, verbose_name='INSTAGRAM URL')),
                ('whatapp_url', models.URLField(blank=True, null=True, verbose_name='WHATSAPP URL')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('pic', models.ImageField(upload_to='Carousel')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span', models.CharField(max_length=10, verbose_name='Year')),
                ('h3', models.CharField(max_length=100, verbose_name='Certificate')),
                ('para', models.TextField()),
                ('school', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('me', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='Galary')),
            ],
        ),
    ]
