# Generated by Django 4.2 on 2023-07-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testing',
            name='i',
        ),
        migrations.AlterField(
            model_name='testing',
            name='h3',
            field=models.CharField(max_length=100, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='testing',
            name='span',
            field=models.CharField(max_length=10, verbose_name='Year'),
        ),
    ]
