# Generated by Django 4.2 on 2023-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0002_remove_testing_i_alter_testing_h3_alter_testing_span'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='Galary')),
            ],
        ),
        migrations.RenameModel(
            old_name='testing',
            new_name='Education',
        ),
    ]
