# Generated by Django 4.2 on 2023-07-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0003_portfolio_rename_testing_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='media/pdf')),
                ('fb_URL', models.URLField(blank=True, null=True, verbose_name='FACEBOOK URL')),
                ('tw_URL', models.URLField(blank=True, null=True, verbose_name='TWITTER URL')),
                ('lk_URL', models.URLField(blank=True, null=True, verbose_name='LINKEDIN URL')),
                ('insta_URL', models.URLField(blank=True, null=True, verbose_name='INSTAGRAM URL')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HmE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.TextField()),
            ],
        ),
    ]
