# Generated by Django 4.2 on 2023-07-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_about_contact_hme'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('me', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='HmE',
        ),
    ]
