# Generated by Django 4.2 on 2023-07-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0005_home_delete_hme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='Carousel')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
