# Generated by Django 4.2 on 2023-07-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0006_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
