# Generated by Django 4.2 on 2023-07-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0007_carousel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.TextField(blank=True, null=True),
        ),
    ]
