# Generated by Django 4.2.3 on 2023-07-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0008_education_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='whatapp_url',
            field=models.URLField(blank=True, null=True, verbose_name='WHATSAPP URL'),
        ),
    ]
